name: Deploy FastAPI App

on:
  push:
    branches:
      - main  # Run when new code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (if any)
        run: |
          pytest || echo "Test failed but continuing deployment..."

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}  # Server IP or domain
          username: ${{ secrets.SERVER_USER }}  # SSH User
          key: ${{ secrets.SERVER_SSH_KEY }}  # SSH Key (stored in GitHub Secrets)
          script: |
            cd /root/path/python_app/AI-SG-TM
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
            echo "FastAPI deployed successfully!"
